Little editing and spelling corrections for documentation.
afterschoolstudio/Depot pull request #30
Opened 2020-12-28 22:20 UTC by darrenkearney

I spotted a few spelling errors and the like when reading through the documentation and thought that I might help out. Seems like a great project!

Best of luck.

Note the Edge Cases WIP second confused me a bit. If you could read over that again and correct it I would be grateful. Thanks!

2020-12-28 22:29 UTC, kkukshtel commented on README.md
> -* When the sheet a line reference field references is deleted, the line value goes to "", the default values are cleared, and the sheet is reset to "".
I _think_ this edit is incorrect, or at least the change you changed it to implies something different. The line is saying that, if you have a `line reference` field, and the sheet you configured that field to select lines _from_ is deleted, the value is updated according to what is stated. It's speaking specifically about `line reference` fields and not `sheet reference` fields. Does that make sense? The wording seems like it could be better - maybe we can add some `preformatted` tags to speak better about the fields?

2020-12-28 22:30 UTC, kkukshtel commented on README.md
> -* When the linw a line reference field references is deleted the lines that pointed to that line get their linked value set to "". Defaults that pointed to that get pointed to ""
This edit, similar to the one above, is also changing the intention of what this is trying to say. It's not talking about the field itself, but the line that has been assigned in the field. Maybe, like above, using preformatted tags may clear this up.

2020-12-28 22:31 UTC, kkukshtel requested changes
Everything looks good besides the Edge Cases section - see the comments there.

2020-12-28 22:40 UTC, darrenkearney commented on README.md
> -* When the linw a line reference field references is deleted the lines that pointed to that line get their linked value set to "". Defaults that pointed to that get pointed to ""
Awesome. I believe you have helped me understand the intention now, which I have included in the latest commit.

2020-12-28 22:41 UTC, darrenkearney reviewed
This should address all the points. :)

2021-01-11 16:51 UTC, kkukshtel requested changes

2021-01-11 16:51 UTC, kkukshtel commented on README.md
> +* When the sheet that a `line reference` field references is deleted, the line value goes to "", the default values are cleared, and the sheet is reset to "".
This one is about sheet references, not about line references. Should be "When the **sheet** a sheet reference field references is deleted..."

2021-09-08 12:37 UTC, kkukshtel commented
Closing this out for now unless the changes are made as suggested.

2021-09-08 12:37 UTC, closed without merging